// import { Inter } from "next/font/google";
// import { Telex } from "next/font/google";
import { Encode_Sans_Expanded } from "next/font/google";

import "./globals.css";

const font = Encode_Sans_Expanded({ weight: ["400", "500", "600"] , subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${font.className} h-[100vh]`}>
      <div className="relative h-[100%] w-full bg-slate-950">
        {children}
        <div className="absolute bottom-0 left-[-20%] right-0 top-[-10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]">
        </div>
        <div className="absolute bottom-0 right-[-20%] top-[-10%] h-[500px] w-[500px] rounded-full bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),rgba(255,255,255,0))]">
        </div>
      </div>
      </body>
    </html>
  );
}
